spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/bracITInterview
    username: admin
    password: admin
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.OracleDialect
